
name: Presubmit

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64

    - uses: actions/checkout@v3

    - name: ktlint
      shell: bash
      run: ./gradlew ktlint

