
name: Presubmit

on:
  pull_request:
    branches: [main]

jobs:
  lint-kotlin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: '11'
        cache: "gradle"


    - name: ktfmtCheck
      shell: bash
      run: ./gradlew ktfmtCheck

  sdk-build:
    runs-on: ubuntu-latest-16-cores
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: '11'
        cache: "gradle"

    - name: Run local tests
      run: ./gradlew test

    - name: Build debug
      run: ./gradlew assembleDebug

    - name: Build release
      run: ./gradlew assembleRelease

    - name: Final check
      run: ./gradlew check

