
name: Presubmit

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: '11'
        cache: "gradle"

    - uses: actions/checkout@v3

    - name: ktlint
      shell: bash
      run: ./gradlew ktlint

